server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #none, create <- 항상 새로 갱신(for test), none <- 일반 테이블!
    properties:
      hibernate:
        show-sql: true
        generate-ddl: true
        format_sql: true
        default_batch_fetch_size: 100   #Maximum = 1000
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

eureka:
  instance:
    instance-id: ${spring.application.name};${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the simple e-commerce

logging:
  level:
    com.example.userservice: DEBUG

token:
  expiration_time: 86400000
  secret: oksk1111@gmail.com